---
title: "The hydraulic P-model"
author: "Victor Flo"
date: "`r Sys.Date()`"
output: html_document
---
  
  
```{r include=FALSE}
library(knitr)
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(scales)
library(sapfluxnetr)
library(xts)
library(viridis)
library(rpmodel)

source("../R/QUADP.R")

knitr::opts_chunk$set(echo = T)
```


#Parameters

```{r}
# path <- "../../0.1.5/RData/plant"
# sfn_meta <- sapfluxnetr::read_sfn_metadata(folder = path, .write_cache = TRUE)
# save(sfn_meta, file = "../sfn_meta.RData")
load(file = "../sfn_meta.RData")

# 
# FRA_PUE <- read_sfn_data("FRA_PUE", folder = path) %>%
#   sfn_metrics(period = "1 hour", .funs = list(~ mean(., na.rm = TRUE)),
#               solar = TRUE, interval = "general")
# 
# save(FRA_PUE, file = "../FRA_PUE.RData")
load(file = "../FRA_PUE.RData")

FRA_PUE_site <- sfn_meta$site_md %>% filter(si_code == "FRA_PUE")
FRA_PUE_stand <- sfn_meta$stand_md %>% filter(si_code == "FRA_PUE")
FRA_PUE_species <- sfn_meta$species_md %>% filter(si_code == "FRA_PUE")
FRA_PUE_plant <- sfn_meta$plant_md %>% filter(si_code == "FRA_PUE")
FRA_PUE_env <- sfn_meta$env_md %>% filter(si_code == "FRA_PUE")

FRA_PUE_df <- FRA_PUE$sapf[,c(1,2)] %>% 
  mutate(pl_code = colnames(.)[2],
    si_code = "FRA_PUE") %>%
  left_join(FRA_PUE$env) %>%
  na.omit() %>%
  left_join(FRA_PUE_site) %>%
  left_join(FRA_PUE_stand) %>% 
  left_join(FRA_PUE_species) %>% 
  left_join(FRA_PUE_plant) %>% 
  mutate(E = .[[2]]/pl_leaf_area/(18*3600)*1e6) #umol m-2 s-1
  
density <- rpmodel::calc_density_h2o(25, 100000)
visco <- rpmodel::calc_viscosity_h2o(25, 100000)

par_plant_std = list(
    Ks0=1e-12, # m2
    v_huber=FRA_PUE_plant$pl_sapw_area[1]/FRA_PUE_plant$pl_leaf_area[1]/10^4, # m2sapwood m-2leaf
    height=FRA_PUE_plant$pl_height[1], # m
    LAI = FRA_PUE_stand$st_lai, # m2leaf m-2soil
    conductivity = 2.63*visco/(1e9*density*55.5), #kmax leaf 2.63 mmol s-1 m-2 MPa-1  to back transform -> kmax*viscosity_water/(1e3*1e6*density*55.5)
    conductivity_scalar=1,  # Scales (Ks0*v_huber/H)
    psi50 = -4.2, # MPa
    b=2
    )

# tc=25
# p = rpmodel::calc_patm(0)
# vpd = 1000

# par_env_std = list(
#   ppfd = 800, 
#   vpd  = vpd,
#   u = 2,
#   ustar = 0.05,
#   nR = 500,
#   co2  = 400,
#   elv  = 0,
#   fapar = 1,
#   patm = p,
#   tc = tc,
#   viscosity_water = rpmodel::calc_viscosity_h2o(tc, p),  # Needs to be imported from rpmodel.R
#   density_water = rpmodel::calc_density_h2o(tc, p) # Needs to be imported from rpmodel.R
# )

get_std_photosythnesis_params = function(){ 
  ## Set P-model parameters
  kphio <- 0.05        # quantum yield efficiency
  # c_molmass <- 12.0107 # molar mass, g / mol
  
  ## Define environmental conditions
  tc <- 25             # temperature, deg C
  ppfd <- 400          # umol/m2/s
  # vpd  <- 1000         # Pa
  co2  <- 400          # ppm
  elv  <- 0            # m.a.s.l.
  fapar <- 0.7         # fraction
  
  p = rpmodel::calc_patm(elv)
  return (list(
    kmm = rpmodel::calc_kmm(tc, p),  # Why does this use std. atm pressure, and not p(z)?
    gammastar = rpmodel::calc_gammastar(tc, p),
    phi0 = kphio*rpmodel::calc_ftemp_kphio(tc),
    Iabs = ppfd*fapar,
    ca = co2*p*1e-6,  # Convert to partial pressure
    patm = p,
    delta = 0.00
  ))
}

par_cost_now = list(
  alpha = 0.1,       # cost of Jmax
  gamma = 1          # cost of hydraulic repair
  )

```


```{r echo = T}

FRA_PUE_df_sub <- FRA_PUE_df %>% slice_head(n=140)
FRA_PUE_df_sub %>% split(seq(nrow(.)))%>% 
  purrr::map(function(x){
    psi_soil <- medfate::soil_psi(medfate::soil(tibble(widths = x$st_soil_depth*10, clay = x$st_sand_perc, sand = x$st_clay_perc, om = NA, bd = 1.6, rfc = 70), W =x$swc_shallow+0.3), model = "SX")
    res <- pmodel_hydraulics_numerical(tc = x$ta, ppfd =x$ppfd_in, vpd = x$vpd*1000, u = x$ws, ustar=NA, nR=x$netrad, co2=400, 
                                elv = x$si_elev, fapar = 0.7, kphio = calc_ftemp_kphio(x$ta), psi_soil = psi_soil, rdark = 0, par_plant = par_plant_std, par_cost = NULL, 
                                opt_hypothesis = "PM", gs_approximation = "PM")
    return(res)
  })%>% bind_rows()->df_PM

FRA_PUE_df_sub %>% split(seq(nrow(.)))%>% 
  purrr::map(function(x){
    psi_soil <- medfate::soil_psi(medfate::soil(tibble(widths = x$st_soil_depth*10, clay = x$st_sand_perc, sand = x$st_clay_perc, om = NA, bd = 1.6, rfc = 70), W =x$swc_shallow+0.3), model = "SX")
    res <- pmodel_hydraulics_numerical(tc = x$ta, ppfd =x$ppfd_in, vpd = x$vpd*1000, u = x$ws, ustar=NA, nR=x$netrad, co2=400, 
                                elv = x$si_elev, fapar = 0.7, kphio = calc_ftemp_kphio(x$ta), psi_soil = psi_soil, rdark = 0, par_plant = par_plant_std, par_cost = NULL, 
                                opt_hypothesis = "PM", gs_approximation = "Ohm")
    return(res)
  })%>% bind_rows()->df_Ohm


p1<-xts::xts(FRA_PUE_df_sub$E, order.by = FRA_PUE_df_sub$TIMESTAMP) %>% plot()
p2<-xts::xts(df_PM$E, order.by = FRA_PUE_df_sub$TIMESTAMP) %>% lines(col="green4")
p3<-xts::xts(df_Ohm$E, order.by = FRA_PUE_df_sub$TIMESTAMP) %>% lines(col="blue4")
p3

```

Black line is sap flow per unit leaf area of an Oak tree from SAPFLUXNET. Green and blue lines are transpiration based on Penman-Monteith and Ohm approximations, respectively. 

```{r echo = T}
FRA_PUE_df_sub2 <- FRA_PUE_df %>% slice_head(n=8000)
FRA_PUE_df_sub2 %>% split(seq(nrow(.)))%>% 
  purrr::map(function(x){
    psi_soil <- medfate::soil_psi(medfate::soil(tibble(widths = x$st_soil_depth*10, clay = x$st_sand_perc, sand = x$st_clay_perc, om = NA, bd = 1.6, rfc = 70), W =x$swc_shallow+0.3), model = "SX")
    res <- pmodel_hydraulics_numerical(tc = x$ta, ppfd =x$ppfd_in, vpd = x$vpd*1000, u = x$ws, ustar=NA, nR=x$netrad, co2=400, 
                                elv = x$si_elev, fapar = 0.7, kphio = calc_ftemp_kphio(x$ta), psi_soil = psi_soil, rdark = 0, par_plant = par_plant_std, par_cost = NULL, 
                                opt_hypothesis = "PM", gs_approximation = "PM")
    return(res)
  })%>% bind_rows()->df_total_PM

FRA_PUE_df_sub2 %>% split(seq(nrow(.)))%>% 
  purrr::map(function(x){
    psi_soil <- medfate::soil_psi(medfate::soil(tibble(widths = x$st_soil_depth*10, clay = x$st_sand_perc, sand = x$st_clay_perc, om = NA, bd = 1.6, rfc = 70), W =x$swc_shallow+0.3), model = "SX")
    res <- pmodel_hydraulics_numerical(tc = x$ta, ppfd =x$ppfd_in, vpd = x$vpd*1000, u = x$ws, ustar=NA, nR=x$netrad, co2=400, 
                                elv = x$si_elev, fapar = 0.7, kphio = calc_ftemp_kphio(x$ta), psi_soil = psi_soil, rdark = 0, par_plant = par_plant_std, par_cost = NULL, 
                                opt_hypothesis = "PM", gs_approximation = "Ohm")
    return(res)
  })%>% bind_rows()->df_total_Ohm

get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}

colnames(df_total_PM) <- paste(colnames(df_total_Ohm), "PM", sep = "_")
colnames(df_total_Ohm) <- paste(colnames(df_total_Ohm), "Ohm", sep = "_")

FRA_PUE_df_sub2 %>% 
  cbind(df_total_PM) %>% 
  mutate(density = get_density(E, E_PM, n = 100)) %>% 
  ggplot(aes(E, E_PM, color = density)) + 
  geom_point() + 
  geom_smooth(method = "lm", linetype = 2, color = "grey20")+
  geom_abline(slope = 1, intercept = 0, color = "grey40")+
  scale_color_viridis()

FRA_PUE_df_sub2 %>% 
  cbind(df_total_Ohm) %>% 
  mutate(density = get_density(E, E_Ohm, n = 100)) %>% 
  ggplot(aes(E, E_Ohm, color = density)) + 
  geom_point() + 
  geom_smooth(method = "lm", linetype = 2, color = "grey20")+
  geom_abline(slope = 1, intercept = 0, color = "grey40")+
  scale_color_viridis()

cor(FRA_PUE_df_sub2$E,df_total_PM$E_PM)
cor(FRA_PUE_df_sub2$E,df_total_Ohm$E_Ohm)

```
